version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
          - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
     - elk

  logstash:
    image: logstash:7.6.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 12201:12201/udp
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - 5601:5601
    networks:
     - elk
    depends_on:
      - elasticsearch
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.6.2
  #   command: filebeat -e -strict.perms=false
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./filebeat/logs:/usr/share/filebeat/logs
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

networks:
  elk:
    driver: bridge